_BASE_: ../../vita/ovis/vita_R50_bs8.yaml
MODEL:
  META_ARCHITECTURE: "Grattvis"
  WEIGHTS: "vita_r50_ovis.pth"
  VITA:
    ENC_WINDOW_SIZE: 0
    FREEZE_DETECTOR: True
  GENVIS:
    LEN_CLIP_WINDOW: 1
    GATED_PROP: True
    USE_MEM: False
    GATE_WEIGHT: 0.0

DATASETS:
  DATASET_RATIO: [1.0, 0.25]
  TRAIN: ( "coco2ovis_train","ovis_train" )
  TEST: ("ovis_val",)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (100000,)
  MAX_ITER: 140000
  CHECKPOINT_PERIOD: 5000
INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 6
  SAMPLING_FRAME_SHUFFLE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 20
