_BASE_: ../../vita/youtubevis_2019/vita_SWIN_bs8.yaml
MODEL:
  META_ARCHITECTURE: "Grattvis"
  WEIGHTS: "vita_swin_ytvis2019.pth"
  VITA:
    ENC_WINDOW_SIZE: 0
    FREEZE_DETECTOR: True
  GENVIS:
    LEN_CLIP_WINDOW: 1
    GATED_PROP: True
    USE_MEM: True
    GATE_WEIGHT: 0.0
DATASETS:
  DATASET_RATIO: [1.0, 0.75]
  TRAIN: ("coco2ytvis2019_train", "ytvis_2019_train")
  TEST: ("ytvis_2019_val",)
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (10000,15000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 6
  SAMPLING_FRAME_SHUFFLE: False
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 10